version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
#      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=incognitoMyth
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    ports:
      - 4306:3306
      #Exposing 4306 for connecting to mysql
  incognito-myth:
    image: incognito-myth
    ports:
      - 8082:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql